### PR TITLE
Use keyPath to read UIApplication.shared to fix issue #80.

### PR DESCRIPTION
**Pull request by abdullahselek**
###  Summary

Thanks for creating this useful library. This is my first PR on this repo and the goal of this PR is to enable usability of PanModal on iOS extensions. #80 

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've written tests to cover the new code and functionality included in this PR.

### CODE REVIEW

**Comment by TosinAF** [comment]
Thanks for making this PR. Will run through the manual regression suite today and if all good, will merge tomorrow. 

Cheers for taking the time!

**Comment by TosinAF** [comment]
Also I’m not so familiar with iOS extensions. Do safe areas still apply?

**Comment by abdullahselek** [comment]
Hi @TosinAF thanks for starting to review my changes. I'm not sure if safe areas still apply on iOS extensions, my solution is to enable building an iOS app with an extension that has a dependency to PanModal.

**Comment by james-ff** [comment]
It *seems* that safe areas apply generally for UIViews despite context (https://stackoverflow.com/questions/46685102/detect-safe-area-insets-on-share-extension)

(I'm not 100% on this, however)

**Comment by rizwan95** [comment]
Is it released to the public?

**Comment by james-ff** [comment]
I believe this just needs a cocoa pod version increase? 🤞

**Comment by rizwan95** [comment]
@TosinAF it will be very helpful for us if it is released!

**Pull request merged**
