### PR TITLE
Improve Swift syntax

### PR DESCRIPTION
**Pull request by giulio92**
###  Summary
This `PR` will:

1. **Reverted in:** 37c4c21  
~Replace `init`-ializable `struct`s with `enum`s~, benefits from this approach can be read in [this](https://github.com/realm/SwiftLint/issues/1871) SwiftLint `PR`.  
2. Add `AnyObject` requirement to `protocol`s
3. Hide a `init?(coder aDecoder: NSCoder)` `func`
4. Few improvements here and there
 
### Requirements
* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've written tests to cover the new code and functionality included in this PR.

### CODE REVIEW

**Comment by TosinAF** [comment]
Hi,

Thanks for doing this. Quick comments,

1. Using an enum instead of a struct is not consistent with our internal app code style guidelines. We should maybe have added as styleguide. Apologies for that.

2. What are the advantages of making the protocols conform to AnyObject?

Cheers,
Tosin

**Comment by giulio92** [comment]
Hi Tosin,

Thanks for your reply. I will answer your comments with a numbered list so it will be easier:

1. While I respect your own code style guidelines, from my own experience I don't think declaring (in those cases) an `enum` instead of a `struct` makes so much difference.
For example:
    ```swift
    struct MyStruct {
        static let myString: String = "I'm a struct"
    }

    enum MyEnum {
        static let myString: String = "I'm a enum"
    }
    ```	

    to retrieve `myString` value you would write:

    ```swift
    let myFirstString: String = MyStruct.myString
    let mySecondString: String = MyEnum.myString
    ```
    the only difference between the two ways is that you cannot `init`-ialize `MyEnum`
    ```swift
    let myStruct: String = MyStruct()    // possible
    let myEnum: String = MyEnum()        // not possible
    ```

2.`PanModalPresentable` and `PanModalPresenter` contains the following delegate `func`s:  
**PanModalPresentable**

- `shouldRespond(to panModalGestureRecognizer: UIPanGestureRecognizer) -> Bool`
- `willRespond(to panModalGestureRecognizer: UIPanGestureRecognizer)`
- `shouldPrioritize(panModalGestureRecognizer: UIPanGestureRecognizer) -> Bool`
- `shouldTransition(to state: PanModalPresentationController.PresentationState) -> Bool`
- `willTransition(to state: PanModalPresentationController.PresentationState)`

**PanModalPresenter**

- `presentPanModal(_ viewControllerToPresent: PanModalPresentable.LayoutType, sourceView: UIView?, sourceRect: CGRect)`

They are meant to be used in a `class` object, as suggested also [here](https://useyourloaf.com/blog/class-only-protocols-in-swift-4/). If you declare a `protocol` non-`AnyObject` anything can conform to it.

Feel free to discuss my reply and I will change the `PR` code accordingly if needed.

Thanks,
Giulio

**Comment by TosinAF** [comment]
@giulio92 thanks for your detailed reply. Makes sense and i agree on both counts. But this repo is upstreamed into the Slack iOS app so, lets take out the enum constants & i'll merge this PR.

Thanks for the AnyObject info. TIL.

**Comment by giulio92** [comment]
Ok @TosinAF! I have reverted commit 1be2e8c with 37c4c21. `PR` should be ready now!

**Comment by TosinAF** [comment]
Awesome thanks! Merged!

**Pull request merged**
