### PR TITLE
Update to Swift 5.0

### PR DESCRIPTION
**Pull request by Awalz**
###  Summary

Describe the goal of this PR. Mention any related Issue numbers.

### Requirements (place an `x` in each `[ ]`)

* [`x` ] I've read and understood the [Contributing Guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [`x` ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

* [ ] I've written tests to cover the new code and functionality included in this PR.

* No functionality was changed from this PR. The test coverage has not been affected

### CODE REVIEW

**Comment by hell4opt** [comment]
+

**Comment by mseijas** [comment]
@ste57 bump! :)

**Comment by nikitskynikita** [comment]
Perhaps it makes sense to add support for Swift 5.1 instead of 5.0?

**Comment by TosinAF** [comment]
Now done. Sorry for the delay. https://github.com/slackhq/PanModal/releases/tag/1.2.5
Will look into 5.1 now.

**Pull request closed without merging**
